#!/bin/bash
# Assemble Astir's own data directory, so a tree built here runs without being
# installed and without reading anything belonging to another program.
#
# Astir is a separate application from Xastir, not a newer version of it.  Both
# can be installed at once, so neither may read the other's resources: a dbfawk
# rule or a symbol table that changes here must not change there, and a change
# there must never silently alter a render here.  Pointing ASTIR_DATA_BASE at
# /usr/share/xastir does exactly that, and it is how the first run after the
# rename appeared to pass -- the shapefiles were being styled by upstream's
# copy of the rules.
#
# What this builds is Astir's, from Astir's tree:
#
#   config/   symbols/   help/      the app's own resources, symlinked to the
#                                   repo so an edit takes effect immediately
#   maps/                           the app's own map directory
#
# The map COLLECTION is different in kind and is not assembled here.  TIGER
# shapefiles are hundreds of megabytes the user downloaded; they are not a
# resource of either program, and which directory they live in is the user's
# choice.  Point ASTIR_MAPS at them and they are linked in; leave it unset and
# Astir starts with only the maps it ships.
#
# ASTIR_MAPS MAY NOT BE ANOTHER PROGRAM'S INSTALL DIRECTORY, and this refuses
# one.  Setting it to /usr/share/xastir/maps looks like it works -- the TIGER
# shapefiles really are in there -- but it also drags in that program's own
# resources, and it did: GPS/ and three attribution images were linked in
# alongside, and then read on every run.  A map collection kept inside a
# package's install prefix is the user's data in the wrong place; copy it out to
# a directory neither program owns and point at that.
#
#   ./tools/devdata.sh
#   ASTIR_DATA_BASE=$PWD/artifacts/datadir ./src/astir
set -eu
cd "$(dirname "$0")/.."

OUT="${1:-artifacts/datadir}"
MAPS_SRC="${ASTIR_MAPS:-}"

# Checked before anything is created or removed, so a refusal leaves the tree
# exactly as it was rather than half-built.
if [ -n "$MAPS_SRC" ]; then
  case "$(cd "$MAPS_SRC" 2>/dev/null && pwd -P || echo "$MAPS_SRC")" in
    */xastir/*|*/xastir)
      echo "refusing ASTIR_MAPS=$MAPS_SRC: that is Xastir's install directory." >&2
      echo "Astir shares no files with it.  Copy your map collection somewhere" >&2
      echo "neither program owns and point ASTIR_MAPS at that instead." >&2
      exit 1
      ;;
  esac
fi

rm -rf "$OUT"
mkdir -p "$OUT/maps"

# Astir's own resources.  Symlinked rather than copied: this is a development
# data directory, and a rule edited in config/ should take effect on the next
# run rather than on the next time somebody remembers to re-run this script.
#
# RELATIVE links, deliberately.  The first version used absolute ones and every
# single link broke the moment the checkout was renamed -- which it was, from
# Xastir to Astir.  A link inside the tree that points at the tree should not
# care where the tree is.
REL=$(python3 -c "import os,sys; print(os.path.relpath('.', sys.argv[1]))" "$OUT")
for d in config symbols help; do
  ln -s "$REL/$d" "$OUT/$d"
done

# The maps Astir itself ships.
ln -s "$REL/../worldhi.map"              "$OUT/maps/worldhi.map"
# The attribution overlay is installed under a third name by a link in
# Makefile.am's install-data-hook; reproduce it, or the OSM layer logs a
# missing file on every render.
ln -s "$REL/../NaturalEarthVector"       "$OUT/maps/NaturalEarth"

# The .geo files describing the online tile servers are generated by make from
# OSM_template, so take them from the build if it has run and the template if
# it has not.
mkdir -p "$OUT/maps/Online"
for g in OSM_tiled_mapnik.geo OSM_tiled_cycle.geo OSM_tiled_fosm.geo; do
  # One level deeper than maps/, so one more ".." than the entries above.
  # Getting this wrong produced dangling links that went unnoticed because the
  # config was still pointing at another application's map directory.
  [ -f "$g" ] && ln -s "$REL/../../$g" "$OUT/maps/Online/$g"
done

# The user's own map collection, wherever they keep it.
if [ -n "$MAPS_SRC" ]; then
  for sub in "$MAPS_SRC"/*; do
    [ -e "$sub" ] || continue
    name="$(basename "$sub")"
    [ -e "$OUT/maps/$name" ] || ln -s "$sub" "$OUT/maps/$name"
  done
  echo "linked the map collection from $MAPS_SRC"
else
  echo "no ASTIR_MAPS set: only the maps Astir ships are present"
fi

echo "built $OUT"
echo "run with:  ASTIR_DATA_BASE=$(pwd)/$OUT ./src/astir"
